name: Report an issue with mantine.dev website
description: Help us find and fix mistakes, bad wording, etc.
labels: 'review required'
body:
  - type: markdown
    attributes:
      value: '## Thanks for reaching out!'
  - type: input
    id: link
    attributes:
      label: Link to the page where something is not right
  - type: textarea
    id: quote
    attributes:
      label: Exact quote of what is wrong
  - type: dropdown
    id: participate
    attributes:
      label: Do you want to send a pull request with a fix?
      options:
        - 'Yes'
        - 'No'
